apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
  labels:
    app: hello-python
    component: web
spec:
  selector:
    matchLabels:
      app: hello-python
      component: web
  template:
    metadata:
      labels:
        app: hello-python
        component: web
    spec:
      containers:
      - name: hello-python
        image: diegoluisi/hello-python
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi